=== dueca/dueca/gitscripts/default/policies.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	   targetNamespace="https://dueca.tudelft.nl"
	   xmlns="https://dueca.tudelft.nl"
	   elementFormDefault="qualified">

  <xs:element name="policies">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="policy" type="policy_t"
		    minOccurs="0" maxOccurs="unbounded"/>
	<xs:element name="policyfile" type="xs:string"
	            minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="policy_t">
    <xs:sequence>
      <xs:element name="description" type="xs:string"
		  minOccurs="0" maxOccurs="1"/>
      <xs:element name="condition" type="condition_t"/>
      <xs:element name="action" type="action_t"
		  minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="id" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="condition_t">
    <xs:sequence>
      <xs:element name="param" type="param_t"
		  minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="condition" type="condition_t"
		  minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="action_t">
    <xs:sequence>
      <xs:element name="param" type="param_t"
		  minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="param_t">
    <xs:simpleContent>
      <xs:extension base="xs:string">
	<xs:attribute name="name" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== dueca/dueca/test/gitscript/example-policies.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
    Example file with some try-out definitions for policy editing.

-->
<policies xmlns="https://dueca.tudelft.nl"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://dueca.tudelft.nl https://dueca.tudelft.nl/schemas/policies.xsd">
  <policy name="replace-dco" id="21-001">
    <description>
      This is a test replacement. Replacing DCO can be used to streamline
      the code base, remove dependency on obsolete projects and the like.
    </description>
    <!-- and combination of conditions -->
    <condition type="and">
      <!-- this checks all comm-objects.lst files in the project, and
           matches on those that have a
           TestProject1/comm-objects/Some.dco line.

           for each match, the result list is filled with a dict
           containing variable dcofile and dcoline
      -->
      <condition type="uses-dco">
        <param name="project">
          TestProject1
        </param>
        <param name="dco">
          Some
        </param>
        <param name="resultvar">
          dcolist
        </param>
      </condition>
      <!-- just to test, check if we have a specific borrowed module -->
      <condition type="has-module">
        <param name="resultvar">
          borrowed_module
        </param>
        <param name="project">
          TestProject1
        </param>
        <param name="module">
          TestModule1
        </param>
      </condition>
    </condition>
    <!-- this action changes the dco use, removes the old_dco
         adds the new dco -->
    <action type="change-dco">
      <param name="mode">replace</param>
      <param name="new_dco">SomeOther</param>
      <param name="new_project">TestProject2</param>
      <param name="inputvar">dcolist</param>
    </action>
  </policy>
  <policy name="to-ignore" id="21-002">
    <description>
      This is a test replacement. Replacing DCO can be used to streamline
      the code base, remove dependency on obsolete projects and the like.
    </description>
    <condition type="constant">
      <param name="value">
        1
      </param>
    </condition>
  </policy>
  <policy name="edit-file" id="21-003">
    <condition type="and">
      <param name="resultvar">
        channel_loc
      </param>
      <param name="inputvar">
        dco_found, channel_loc_header
      </param>
      <param name="result-filename">
        channel_loc_header
      </param>
      <param name="result-matches">
        channel_loc_header
      </param>
      <param name="match">
        module
      </param>
      <condition type="uses-dco">
        <param name="project">
          TestProject2
        </param>
        <param name="dco">
          Other
        </param>
        <param name="resultvar">
          dco_found
        </param>
      </condition>
      <condition type="find-pattern">
        <param name="fileglob">
          */SomeModule.hxx
        </param>
        <param name="pattern">
          private: // channel access[\n]
        </param>
        <param name="resultvar">
          channel_loc_header
        </param>
      </condition>
    </condition>
    <action type="insert-text">
      <param name="inputvar">
        channel_loc
      </param>
      <param name="text">
        ChannelReadToken r_some;
      </param>
      <param name="mode">after</param>
    </action>
  </policy>
  <policy name="edit-file2" id="21-004">
    <condition type="find-pattern">
      <param name="fileglob">
        */SomeModule.cxx
      </param>
      <param name="pattern">
        // various parameters. Some examples:
      </param>
      <param name="resultvar">
        channel_loc
      </param>
    </condition>
    <action type="insert-text">
      <param name="inputvar">
        channel_loc
      </param>
      <param name="text">
        r_some(getId(), NameSet(getEntity(), Some::classname, part),
        Some::classname, 0, Channel::Events),
      </param>
      <param name="mode">after</param>
    </action>
  </policy>
</policies>

=== dueca/dueca/test/gitscript/homedco.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
    Re-write the dco lines for dco objects that are from the same project as
    the module in which it is used; omit the module part.
-->
<policies xmlns="https://dueca.tudelft.nl"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://dueca.tudelft.nl https://dueca.tudelft.nl/schemas/policies.xsd">
  <policy name="home-dco" id="24-001">
    <description>
      From dueca 4.0.9, comm-objects.lst files interpretation is more flexible
      A line with only the name of a dco object (with .dco extension, and
      optionally a comment), will be interpreted to include a dco object from
      the "home" project, i.e., the project that also supplies the module.

      This policy will search for dco lines where the project matches the
      home project, and produce a match list, which can then be used to
      re-write the comm-objects.lst file, removing the project part from the
      dco specification.

      The advantage is that a project may be copied/cloned, and that the used
      dco's will no longer be pulled from the original project.
    </description>
    <condition type="home-dco">
      <!-- any dco -->
      <param name="dco" regex="true">
        ^[a-zA-Z0-9_]+$
      </param>
      <param name="resultvar">
        homedco
      </param>
    </condition>
    <action type="change-dco">
      <param name="inputvar">
        homedco
      </param>
      <!-- new-dco is a match, result is the current dco name -->
      <param name="new_dco" format="true">
        {dco}
      </param>
      <!-- new_project is not set, will be "None", and not written -->
      <!-- mode replace -->
      <param name="mode">
        replace
      </param>
    </action>
  </policy>
  <policy name="home-depend" id="24-002">
    <description>
      From dueca 4.0.9, CMakeLists.txt files interpretation is more flexible
      A USEMODULES line with only the name of a module will be interpreted
      to include a module from the "home" project, i.e., the project that
      also supplies the module.

      The advantage is that a project may be copied/cloned, and that the used
      modules no longer be pulled from the original project.
    </description>
    <condition type="home-depend">
      <param name="resultvar">
        homedepend
      </param>
    </condition>
    <action type="insert-text">
      <param name="inputvar">homedepend</param>
      <param name="mode">replace</param>
      <param name="text" format="true">{g2} # policy 24-002 {g3}</param>
    </action>
  </policy>
</policies>

=== dueca/dueca/test/gitscript/worldviewdco.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
    Example file with some try-out definitions for policy editing.

-->
<policies xmlns="https://dueca.tudelft.nl"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://dueca.tudelft.nl https://dueca.tudelft.nl/schemas/policies.xsd">

  <policy name="replace-worldview-dco-motion" id="21-001">
    <description>
      While WorldView is a commonly-used module, it at one point
      relied on DCO objects from WorldListener; it was more efficient
      to move this to WorldView
    </description>
    <condition type="uses-dco">
      <param name="dco">
        BaseObjectMotion
      </param>
      <param name="project">
        WorldListener
      </param>
      <param name="resultvar">
        dcolist
      </param>
    </condition>
    <action type="change-dco">
      <param name="new_dco">
        BaseObjectMotion
      </param>
      <param name="new_project">
        WorldView
      </param>
      <param name="inputvar">
        dcolist
      </param>
      <param name="mode">replace</param>
    </action>
  </policy>

  <policy name="replace-worldview-dco-position" id="21-002">
    <description>
      While WorldView is a commonly-used module, it at one point
      relied on DCO objects from WorldListener; it was more efficient
      to move these to WorldView
    </description>

    <!-- detects a WorldListener/comm-objects/BaseObjectPosition
         borrowed anywhere -->
    <condition type="uses-dco">
      <param name="dco">
        BaseObjectPosition
      </param>
      <param name="project">
        WorldListener
      </param>
      <param name="resultvar">
        dcolist
      </param>
    </condition>

    <!-- removes WorldListener/comm-objects/BaseObjectPosition, and add
	 WorldView/comm-objects/BaseObjectPosition -->
    <action type="change-dco">
      <param name="mode">
        replace
      </param>
      <param name="new_dco">
        BaseObjectPosition
      </param>
      <param name="new_project">
        WorldView
      </param>
      <param name="inputvar">
        dcolist
      </param>
    </action>
  </policy>


  <policy name="add-worldview-dco-position" id="21-003">
    <description>
      Old WorldView had ObjectMotion objects that did not inherit. Later
      these objects inherited from BaseObjectPosition and BaseObjectMotion.
      Add the relevant parents if not found in a comm-objects.lst file
    </description>
    <condition type="and">

      <!-- match on filename (dco file), and pass the dcolist parameter
	   from the first list -->
      <param name="match">
        filename
      </param>
      <param name="inputvar">
	dcolist_uses, dcolist_notcorrected
      </param>
      <param name="resultvar">
	dcolist
      </param>
      <param name="result-dcolist">
	dcolist_uses
      </param>

      <condition type="uses-dco">
        <param name="dco">
          ObjectMotion
        </param>
        <param name="project">
          WorldView
        </param>
        <param name="resultvar">
          dcolist_uses
        </param>
      </condition>

      <!-- detect where the objects have not yet been added -->
      <condition type="not">
	<param name="inputvar">
	  dcolist_complete
	</param>
        <param name="resultvar">
          dcolist_notcorrected
        </param>

        <condition type="and">
	  <param name="inputvar">
	    have_bop, have_bom
	  </param>
	  <param name="match">
	    filename
	  </param>
          <param name="resultvar">
            dcolist_complete
          </param>
          <condition type="uses-dco">
            <param name="dco">
              BaseObjectMotion
            </param>
            <param name="project">
              WorldView
            </param>
	    <param name="resultvar">
	      have_bom
	    </param>
          </condition>
          <condition type="uses-dco">
            <param name="dco">
              BaseObjectPosition
            </param>
            <param name="project">
              WorldView
            </param>
	    <param name="resultvar">
	      have_bop
	    </param>
          </condition>
        </condition>
      </condition>
    </condition>
    <action type="change-dco">
      <param name="new_dco">
        BaseObjectPosition
      </param>
      <param name="new_project">
        WorldView
      </param>
      <param name="inputvar">
        dcolist
      </param>
      <param name="mode">add</param>
    </action>
    <action type="change-dco">
      <param name="new_dco">
        BaseObjectMotion
      </param>
      <param name="new_project">
        WorldView
      </param>
      <param name="inputvar">
        dcolist
      </param>
      <param name="mode">add</param>
    </action>
  </policy>


  <policy name="add-worldview-specbase" id="21-004">
    <description>
      Base objects for specifying the data (file names, numbers,
      positions, etc.) for audio and video events uses the same set of
      code. This used to be merged in the WorldView module, but has
      now been extracted.
    </description>

    <condition type="and">

      <!-- Combine on filename, look per machine class -->
      <param name="match">
        filename
      </param>
      <!-- Result variable is a list with filenames pointing to the
           modules.xml files, and a "modules" member that has a DUECAUTILS
           Modules class defining the machine. -->
      <param name="resultvar" trim="true">
        modlist
      </param>
      <param name="inputvar">
        modlisto, modlistn
      </param>
      <param name="result-modules">
        modlisto
      </param>

      <!-- OR condition; either borrow the WorldView/WorldView, or the
           WorldListener/WorldListener module -->
      <condition type="or">

        <!-- Combine on filename, has the effect of looking per machine class -->
        <param name="match">
          filename
        </param>
        <param name="resultvar">
          modlisto
        </param>
        <param name="inputvar">
          modlist1,modlist2
        </param>
        <param name="match">
          filename
        </param>
        <param name="result-modules">
          modlist1
        </param>

        <!-- Test for WorldView/WorldView, result in modlist1 -->
        <condition type="has-module">
          <param name="all_machines">
            true
          </param>
          <param name="project">
            WorldView
          </param>
          <param name="module">
            WorldView
          </param>
          <param name="resultvar">
            modlist1
          </param>
        </condition>

        <!-- Test for WorldListener/WorldListener, result in modlist2 -->
        <condition type="has-module">
          <param name="all_machines">
            true
          </param>
           <param name="project">
            WorldListener
          </param>
          <param name="module">
            WorldListener
          </param>
          <param name="resultvar">
            modlist2
          </param>
        </condition>

      </condition> <!-- and or -->

      <!-- Check that the WorldView/SpecificationBase is not yet present -->
      <condition type="not">
        <condition type="has-module">
          <param name="all_machines">
            true
          </param>
           <param name="project">
            WorldView
          </param>
          <param name="module">
            SpecificationBase
          </param>
          <param name="resultvar">
            modlistn
          </param>
        </condition>
      </condition>

    </condition>

    <!-- Action to add the WorldView/SpecificationBase module to the
         modules.xml list where this is missing, and the WorldView or
         WorldListener module is used.

         It uses the modlist list of results, and specifically the
         modules variable in there to access the modules.xml
         representation. -->
    <action type="change-module">
      <param name="new_project">
        WorldView
      </param>
      <param name="new_module">
        SpecificationBase
      </param>
      <param name="inputvar">
        modlist
      </param>
    </action>
  </policy>

</policies>

=== dueca/dueca/gitscripts/default/policy_example.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
    Example file with some try-out definitions for policy editing.

-->
<policies xmlns="https://dueca.tudelft.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://dueca.tudelft.nl policies.xsd">
  <policy name="replace-worldview-dco-motion" id="21-001">
    <description>
      While WorldView is a commonly-used module, it relies on DCO objects
      from WorldListener; it is more efficient to move this to WorldView
    </description>
    <condition type="uses-dco">
      <param name="dco">
        BaseObjectMotion
      </param>
      <param name="project">
	WorldListener
      </param>
      <param name="resultvar">
	dcolist
      </param>
    </condition>
    <action type="change-dco">
      <param name="old_dco">
	BaseObjectMotion
      </param>
      <param name="old_project">
	WorldListener
      </param>
      <param name="new_dco">
	BaseObjectMotion
      </param>
      <param name="new_project">
	WorldView
      </param>
      <param name="inputvar">
	dcolist
      </param>
    </action>
  </policy>
  <policy name="replace-worldview-dco-position" id="21-002">
    <description>
      While WorldView is a commonly-used module, it relies on DCO objects
      from WorldListener; it is more efficient to move this to WorldView
    </description>
    <condition type="uses-dco">
      <param name="dco">
        BaseObjectPosition
      </param>
      <param name="project">
	WorldListener
      </param>
      <param name="resultvar">
	dcolist
      </param>
    </condition>
    <action type="change-dco">
      <param name="old_dco">
	BaseObjectPosition
      </param>
      <param name="old_project">
	WorldListener
      </param>
      <param name="new_dco">
	BaseObjectPosition
      </param>
      <param name="new_project">
	WorldView
      </param>
      <param name="inputvar">
	dcolist
      </param>
    </action>
  </policy>
  <policy name="add-worldview-dco-position" id="21-003">
    <description>
      Old WorldView had ObjectMotion objects that did not inherit. Later
      these objects inherited from BaseObjectPosition and BaseObjectMotion.
      Add the relevant parents if not found in the comm-objects.lst
    </description>
    <condition type="and">
      <condition type="uses-dco">
	<param name="dco">
          ObjectMotion
	</param>
	<param name="project">
	  WorldView
	</param>
	<param name="resultvar">
	  dcolist
	</param>
      </condition>
      <condition type="not">
	<condition type="and">
	  <condition type="uses-dco">
	    <param name="dco">
              BaseObjectMotion
	    </param>
	    <param name="project">
	      WorldView
	    </param>
	  </condition>
	  <condition type="uses-dco">
	    <param name="dco">
              BaseObjectPosition
	    </param>
	    <param name="project">
	      WorldView
	    </param>
	  </condition>
	</condition>
      </condition>
    </condition>
    <action type="change-dco">
      <param name="new_dco">
	BaseObjectPosition
      </param>
      <param name="new_project">
	WorldView
      </param>
      <param name="inputvar">
	dcolist
      </param>
    </action>
    <action type="change-dco">
      <param name="new_dco">
	BaseObjectMotion
      </param>
      <param name="new_project">
	WorldView
      </param>
      <param name="inputvar">
	dcolist
      </param>
    </action>
  </policy>

  <policy name="add-worldview-specbase" id="21-004">
    <condition type="and">
      <condition type="or">
	<param name="resultvar">
	  modlist
	</param>
	<param name="inputvar">
	  modlist1,modlist2
	</param>
	<condition type="has-module">
	  <param name="project">
	    WorldView
	  </param>
	  <param name="module">
	    WorldView
	  </param>
	  <param name="resultvar">
	    modlist1
	  </param>
	</condition>
	<condition type="has-module">
	  <param name="project">
	    WorldListener
	  </param>
	  <param name="module">
	    WorldListener
	  </param>
	  <param name="resultvar">
	    modlist2
	  </param>
	</condition>
      </condition>
      <condition type="not">
	<condition type="has-module">
	  <param name="project">
	    WorldView
	  </param>
	  <param name="module">
	    SpecificationBase
	  </param>
	</condition>
      </condition>
    </condition>
    <action type="change-module">
      <param name="new_project">
	WorldView
      </param>
      <param name="new_module">
	SpecificationBase
      </param>
      <param name="inputvar">
	modlist
      </param>
    </action>
  </policy>
</policies>

=== dueca/dueca/gitscripts/default/homedco.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
    Re-write the dco lines for dco objects that are from the same project as
    the module in which it is used; omit the module part.
-->
<policies xmlns="https://dueca.tudelft.nl/policies"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://dueca.tudelft.nl/policies https://dueca.tudelft.nl/schemas/policies.xsd">
  <policy name="home-dco" id="24-001">
    <description>
      From dueca 4.0.9, comm-objects.lst files interpretation is more flexible
      A line with only the name of a dco object (with .dco extension, and
      optionally a comment), will be interpreted to include a dco object from
      the "home" project, i.e., the project that also supplies the module.

      This policy will search for dco lines where the project matches the
      home project, and produce a match list, which can then be used to
      re-write the comm-objects.lst file, removing the project part from the
      dco specification.

      The advantage is that a project may be re-named or forked, and that the used
      dco's will no longer be pulled from the original project.
    </description>
    <condition type="home-dco">
      <!-- any dco -->
      <param name="dco" regex="true">
        (^[a-zA-Z0-9_]+)$
      </param>
      <!-- from any project -->
      <param name="project" regex="true">
        ^[a-zA-Z0-9_]+$
      </param>
      <param name="resultvar">
        homedco
      </param>
    </condition>
    <action type="change-dco">
      <param name="inputvar">
        homedco
      </param>
      <!-- setting old_dco empty ensures it will be changed (commented out -->
      <param name="old_dco">
      </param>
      <!-- new-dco is a match, result is the current dco name -->
      <param name="new_dco" format="true">
        {g1}
      </param>
      <!-- new_project is not set, will be "None", and not written -->
    </action>
  </policy>
  <policy name="home-include" id="24-002">
    <description>
      From DUECA 4.0.9, the interpretation of including / dependency on another module
      is more flexible. The module name can be supplied without project name, in that
      case it is assumed that the module is from the home project. Doing this also
      simplfies re-naming / forking a project.
    </description>
    <condition type="home-depend">
      <param name="resultvar">
        homedepend
      </param>
    </condition>
    <action type="insert-text">
      <param name="inputvar">homedepend</param>
      <param name="mode">replace</param>
      <param name="text" format="true">{g1}</param>
    </action>
  </policy>
</policies>
