=== dueca/dueca/gitscripts/default/testscenario.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://dueca.tudelft.nl"
  xmlns="https://dueca.tudelft.nl"
  elementFormDefault="qualified">

  <xs:element name="scenario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="project" type="project_t"
          minOccurs="1" maxOccurs="1" />
        <xs:element name="repository" type="xs:string"
          minOccurs="1" maxOccurs="1" />
        <xs:element name="version" type="xs:string"
          minOccurs="0" maxOccurs="1" />
        <xs:element name="execute" type="execute_t"
          minOccurs="1" maxOccurs="unbounded" />
        <xs:element name="offset" type="offset_t"
          minOccurs="0" maxOccurs="1" />
        <xs:element name="actions" type="actions_t"
          minOccurs="1" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="project_t">
    <xs:sequence>
      <xs:element name="window" type="xs:string"
        minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="execute_t">
    <xs:sequence>
      <xs:element name="platform" type="xs:string"
        minOccurs="1" maxOccurs="1" />
      <xs:element name="node" type="xs:string"
        minOccurs="1" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="actions_t">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="click" type="click_t" minOccurs="1" maxOccurs="1" />
      <xs:element name="check" type="check_t" minOccurs="1" maxOccurs="1" />
      <xs:element name="snap" type="snap_t" minOccurs="1" maxOccurs="1" />
      <xs:element name="key" type="key_t" minOccurs="1" maxOccurs="1" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="offset_t">
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
  </xs:complexType>

  <xs:complexType name="check_t">
    <xs:attribute name="window" type="xs:string" />
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
    <xs:attribute name="r" type="xs:integer" />
    <xs:attribute name="g" type="xs:integer" />
    <xs:attribute name="b" type="xs:integer" />
    <xs:attribute name="timeout" type="xs:decimal" />
    <xs:attribute name="wait" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="click_t">
    <xs:attribute name="window" type="xs:string" />
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
    <xs:attribute name="button" type="xs:string" />
    <xs:attribute name="pressed" type="xs:boolean" />
    <xs:attribute name="wait" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="key_t">
    <xs:attribute name="window" type="xs:string" />
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
    <xs:attribute name="key" type="xs:string" />
    <xs:attribute name="wait" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="snap_t">
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>

</xs:schema>

=== dueca/dueca/test/runtest/tmswsfour.xml
<?xml version='1.0' encoding='UTF-8'?>
<scenario xmlns="https://dueca.tudelft.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://dueca.tudelft.nl https://dueca.tudelft.nl/schemas/testscenario.xsd">
  <project name="DuecaTestCommunication">
    <window>DUECA/DUSIME control panel</window>
    <window>Are you serious?</window>
  </project>
  <repository>git@gitlab.tudelft.nl:rvanpaassen/</repository>
  <execute>
    <platform>udpws-four</platform>
    <node>node4</node>
  </execute>
  <execute>
    <platform>udpws-four</platform>
    <node>node3</node>
  </execute>
  <execute>
    <platform>udpws-four</platform>
    <node>node2</node>
  </execute>
  <execute>
    <platform>udpws-four</platform>
    <node>node1</node>
  </execute>
  <offset x="1" y="-15"/>
  <actions>
    <snap name="tmswsfour-run0.png"/>
    <check window="DUECA/DUSIME control panel" x="475" y="35" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="474" y="75" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="474" y="75" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="474" y="75" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="475" y="76" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="475" y="119" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="475" y="119" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="475" y="119" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="475" y="119" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="476" y="161" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="474" y="201" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="474" y="201" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="474" y="201" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="477" y="202" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="422" y="203" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="422" y="203" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="422" y="203" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="422" y="203" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="475" y="204" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="475" y="243" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="475" y="243" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="475" y="243" button="Button.left" pressed="false" wait="0.2"/>
    <snap name="tmswsfour-run1.png"/>
    <check window="DUECA/DUSIME control panel" x="475" y="246" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="475" y="201" r="104" g="104" b="104" timeout="10.0" wait="10.5"/>
    <click window="DUECA/DUSIME control panel" x="475" y="201" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="475" y="201" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="475" y="205" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="475" y="160" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="475" y="160" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="475" y="160" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="475" y="77" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="475" y="77" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="475" y="77" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="475" y="77" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="475" y="33" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="475" y="33" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="475" y="33" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="31" y="-17" r="250" g="250" b="250" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="31" y="-17" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="31" y="-17" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="69" y="36" r="222" g="222" b="222" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="69" y="36" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="69" y="36" button="Button.left" pressed="false" wait="0.2"/>
    <check window="Are you serious?" x="70" y="36" r="245" g="245" b="245" timeout="10.0" wait="0.5"/>
    <click window="Are you serious?" x="70" y="36" button="Button.left" pressed="true" wait="0.2"/>
    <click x="114" y="224" button="Button.left" pressed="false" wait="0.2"/>
    <click x="114" y="224" button="Button.left" pressed="true" wait="0.2"/>
  </actions>
</scenario>

=== dueca/dueca/test/runtest/dtcwebsock.xml
<?xml version='1.0' encoding='UTF-8'?>
<scenario xmlns="https://dueca.tudelft.nl/testscenario"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://dueca.tudelft.nl/testscenario https://dueca.tudelft.nl/schemas/testscenario.xsd">
  <project name="DuecaTestCommunication">
    <window>DUECA/DUSIME control panel</window>
    <window>Are you serious?</window>
  </project>
  <repository>https://github.com/dueca/</repository>
  <buildoptions>-DUSE_GTK3=ON</buildoptions>
  <execute>
    <platform>solo</platform>
    <node>websock</node>
  </execute>
  <offset x="1" y="-10" />
  <actions>
    <check window="DUECA/DUSIME control panel" x="476" y="36" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="476" y="75" r="104" g="104" b="104" timeout="10.0"
      wait="0.5" />
    <snap name="dtcwebsock000.png" />
    <click window="DUECA/DUSIME control panel" x="476" y="75" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="476" y="75" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="DUECA/DUSIME control panel" x="476" y="75" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="475" y="118" r="104" g="104" b="104"
      timeout="10.0" wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="475" y="118" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="475" y="118" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="DUECA/DUSIME control panel" x="475" y="118" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="476" y="163" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="475" y="201" r="104" g="104" b="104"
      timeout="10.0" wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="475" y="201" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="475" y="201" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="DUECA/DUSIME control panel" x="475" y="202" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="423" y="201" r="104" g="104" b="104"
      timeout="10.0" wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="423" y="201" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="423" y="201" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="DUECA/DUSIME control panel" x="423" y="201" r="104" g="104" b="104"
      timeout="10.0" wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="475" y="203" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="475" y="244" r="104" g="104" b="104"
      timeout="10.0" wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="475" y="244" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="475" y="244" button="Button.left" pressed="false"
      wait="0.2" />
    <snap name="dtcwebsock001.png" />
    <check window="DUECA/DUSIME control panel" x="476" y="244" r="65" g="255" b="11" timeout="10.0"
      wait="10.5" />
    <check window="DUECA/DUSIME control panel" x="476" y="201" r="104" g="104" b="104"
      timeout="10.0" wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="476" y="201" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="476" y="201" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="DUECA/DUSIME control panel" x="476" y="204" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="475" y="161" r="104" g="104" b="104"
      timeout="10.0" wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="475" y="161" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="475" y="161" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="DUECA/DUSIME control panel" x="475" y="161" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="477" y="118" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="476" y="75" r="104" g="104" b="104" timeout="10.0"
      wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="476" y="75" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="476" y="75" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="DUECA/DUSIME control panel" x="476" y="75" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="476" y="33" r="104" g="104" b="104" timeout="10.0"
      wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="476" y="33" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="476" y="33" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="DUECA/DUSIME control panel" x="476" y="33" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="35" y="-18" r="246" g="245" b="244" timeout="10.0"
      wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="31" y="-18" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="31" y="-18" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="DUECA/DUSIME control panel" x="60" y="35" r="53" g="132" b="228" timeout="10.0"
      wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="60" y="35" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="60" y="35" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="Are you serious?" x="12" y="26" r="248" g="248" b="247" timeout="10.0" wait="0.5" />
    <click window="Are you serious?" x="12" y="26" button="Button.left" pressed="true" wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="144" y="155" button="Button.left" pressed="false"
      wait="0.2" />
  </actions>
</scenario>

=== dueca/dueca/test/runtest/testscenario.xml
<?xml version='1.0' encoding='UTF-8'?>
<scenario xmlns="https://dueca.tudelft.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://dueca.tudelft.nl testscenario.xsd">
  <project name="FlexiStick">
    <window>DUECA/DUSIME control panel</window>
    <window>HID feedback</window>
    <window>Are you serious?</window>
  </project>
  <execute>
    <platform>solo</platform>
    <node>solo</node>
  </execute>
  <actions>
    <check window="HID feedback" x="13" y="14" r="0" g="0" b="0" timeout="5.0"/>
    <click window="HID feedback" x="13" y="14" button="Button.left" pressed="true"/>
    <click window="HID feedback" x="13" y="14" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="468" y="102" r="246" g="245" b="244" timeout="5.0"/>
    <click window="DUECA/DUSIME control panel" x="431" y="17" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="431" y="17" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="464" y="101" r="246" g="245" b="244" timeout="5.0"/>
    <click window="DUECA/DUSIME control panel" x="468" y="147" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="468" y="147" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="468" y="147" r="191" g="191" b="189" timeout="5.0"/>
    <click window="DUECA/DUSIME control panel" x="466" y="185" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="466" y="185" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="466" y="184" r="191" g="191" b="189" timeout="5.0"/>
    <click window="DUECA/DUSIME control panel" x="464" y="143" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="464" y="143" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="464" y="143" r="191" g="191" b="189" timeout="5.0"/>
    <click window="DUECA/DUSIME control panel" x="465" y="104" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="465" y="104" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="465" y="104" r="246" g="245" b="244" timeout="5.0"/>
    <click window="DUECA/DUSIME control panel" x="14" y="53" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="14" y="53" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="75" y="107" r="145" g="148" b="149" timeout="5.0"/>
    <click window="DUECA/DUSIME control panel" x="75" y="107" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="75" y="107" button="Button.left" pressed="false"/>
    <check window="Are you serious?" x="29" y="83" r="156" g="159" b="159" timeout="5.0"/>
    <click window="Are you serious?" x="29" y="83" button="Button.left" pressed="true"/>
    <click window="Are you serious?" x="29" y="83" button="Button.left" pressed="false"/>
  </actions>
</scenario>
