=== dueca/dueca/gitscripts/default/testscenario.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://dueca.tudelft.nl"
  xmlns="https://dueca.tudelft.nl"
  elementFormDefault="qualified">

  <xs:element name="scenario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="project" type="project_t"
          minOccurs="1" maxOccurs="1" />
        <xs:element name="repository" type="xs:string"
          minOccurs="1" maxOccurs="1" />
        <xs:element name="version" type="xs:string"
          minOccurs="0" maxOccurs="1" />
        <xs:element name="execute" type="execute_t"
          minOccurs="1" maxOccurs="unbounded" />
        <xs:element name="offset" type="offset_t"
          minOccurs="0" maxOccurs="1" />
        <xs:element name="actions" type="actions_t"
          minOccurs="1" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="project_t">
    <xs:sequence>
      <xs:element name="window" type="xs:string"
        minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="execute_t">
    <xs:sequence>
      <xs:element name="platform" type="xs:string"
        minOccurs="1" maxOccurs="1" />
      <xs:element name="node" type="xs:string"
        minOccurs="1" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="actions_t">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="click" type="click_t" minOccurs="1" maxOccurs="1" />
      <xs:element name="check" type="check_t" minOccurs="1" maxOccurs="1" />
      <xs:element name="snap" type="snap_t" minOccurs="1" maxOccurs="1" />
      <xs:element name="key" type="key_t" minOccurs="1" maxOccurs="1" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="offset_t">
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
  </xs:complexType>

  <xs:complexType name="check_t">
    <xs:attribute name="window" type="xs:string" />
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
    <xs:attribute name="r" type="xs:integer" />
    <xs:attribute name="g" type="xs:integer" />
    <xs:attribute name="b" type="xs:integer" />
    <xs:attribute name="timeout" type="xs:decimal" />
    <xs:attribute name="wait" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="click_t">
    <xs:attribute name="window" type="xs:string" />
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
    <xs:attribute name="button" type="xs:string" />
    <xs:attribute name="pressed" type="xs:boolean" />
    <xs:attribute name="wait" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="key_t">
    <xs:attribute name="window" type="xs:string" />
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
    <xs:attribute name="key" type="xs:string" />
    <xs:attribute name="wait" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="snap_t">
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>

</xs:schema>

=== dueca/dueca/test/runtest/tmsudpfour.xml
<?xml version='1.0' encoding='UTF-8'?>
<scenario xmlns="https://dueca.tudelft.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://dueca.tudelft.nl testscenario.xsd">
  <project name="DuecaTestCommunication">
    <window>DUECA/DUSIME control panel</window>
    <window>Are you serious?</window>
  </project>
  <repository>https://github.com/dueca/</repository>
  <execute>
    <platform>udpws-four</platform>
    <node>node4</node>
  </execute>
  <execute>
    <platform>udpws-four</platform>
    <node>node3</node>
  </execute>
  <execute>
    <platform>udpws-four</platform>
    <node>node2</node>
  </execute>
   <execute>
    <platform>udpws-four</platform>
    <node>node1</node>
  </execute>
 <actions>
    <check window="DUECA/DUSIME control panel" x="478" y="61" r="65" g="255" b="11" timeout="15.0" wait="10.5"/>
    <click window="DUECA/DUSIME control panel" x="477" y="108" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="477" y="108" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="477" y="108" r="65" g="255" b="11" timeout="5.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="482" y="150" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="482" y="150" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="482" y="150" r="65" g="255" b="11" timeout="5.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="478" y="233" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="478" y="233" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="478" y="233" r="65" g="255" b="11" timeout="5.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="428" y="231" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="428" y="231" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="478" y="232" r="65" g="255" b="11" timeout="5.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="479" y="275" r="104" g="104" b="104" timeout="5.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="479" y="275" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="479" y="275" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="478" y="275" r="65" g="255" b="11" timeout="5.0" wait="10.5"/>
    <snap name="tmssolo-run.png"/>
    <click window="DUECA/DUSIME control panel" x="479" y="234" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="479" y="234" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="479" y="233" r="65" g="255" b="11" timeout="5.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="478" y="191" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="478" y="191" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="478" y="191" r="65" g="255" b="11" timeout="5.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="476" y="108" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="476" y="108" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="476" y="108" r="65" g="255" b="11" timeout="5.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="478" y="67" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="478" y="67" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="478" y="67" r="65" g="255" b="11" timeout="5.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="24" y="10" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="24" y="10" button="Button.left" pressed="false"/>
    <check window="DUECA/DUSIME control panel" x="55" y="67" r="53" g="132" b="228" timeout="5.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="79" y="65" r="53" g="132" b="228" timeout="5.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="79" y="65" button="Button.left" pressed="true"/>
    <click window="DUECA/DUSIME control panel" x="79" y="65" button="Button.left" pressed="false"/>
    <check window="Are you serious?" x="15" y="58" r="248" g="248" b="247" timeout="5.0" wait="0.5"/>
    <click window="Are you serious?" x="15" y="58" button="Button.left" pressed="true"/>
    <click window="Are you serious?" x="15" y="58" button="Button.left" pressed="false"/>
  </actions>
</scenario>

=== dueca/dueca/test/runtest/tmsudptwo.xml
<?xml version='1.0' encoding='UTF-8'?>
<scenario xmlns="https://dueca.tudelft.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://dueca.tudelft.nl https://dueca.tudelft.nl/schemas/testscenario.xsd">
  <project name="DuecaTestCommunication">
    <window>DUECA/DUSIME control panel</window>
    <window>Are you serious?</window>
  </project>
  <repository>https://github.com/dueca/</repository>
  <execute>
    <platform>udp-two</platform>
    <node>node2</node>
  </execute>
  <execute>
    <platform>udp-two</platform>
    <node>node1</node>
  </execute>
  <offset x="1" y="-15"/>
  <actions>
    <snap name="tmsudptwo-start.png"/>
    <check window="DUECA/DUSIME control panel" x="477" y="34" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="474" y="77" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="474" y="77" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="474" y="77" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="474" y="77" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="474" y="117" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="474" y="117" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="474" y="117" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="474" y="163" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="475" y="201" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="475" y="201" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="475" y="201" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="475" y="201" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="423" y="199" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="423" y="199" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="423" y="199" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="476" y="204" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="476" y="243" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="476" y="243" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="476" y="243" button="Button.left" pressed="false" wait="0.2"/>
    <snap name="tmsudptwo-running.png"/>
    <check window="DUECA/DUSIME control panel" x="474" y="202" r="104" g="104" b="104" timeout="10.0" wait="10.5"/>
    <click window="DUECA/DUSIME control panel" x="474" y="202" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="474" y="202" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="475" y="160" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="475" y="160" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="475" y="160" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="476" y="74" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="476" y="74" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="476" y="74" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="476" y="33" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="476" y="33" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="476" y="33" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="32" y="-17" r="250" g="250" b="250" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="32" y="-17" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="32" y="-17" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="68" y="37" r="222" g="222" b="222" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="68" y="37" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="68" y="37" button="Button.left" pressed="false" wait="0.2"/>
    <check window="Are you serious?" x="87" y="37" r="245" g="245" b="245" timeout="10.0" wait="0.5"/>
    <click window="Are you serious?" x="87" y="37" button="Button.left" pressed="true" wait="0.2"/>
    <click x="131" y="225" button="Button.left" pressed="false" wait="0.2"/>
    <click x="131" y="225" button="Button.left" pressed="true" wait="0.2"/>
  </actions>
</scenario>

=== dueca/dueca/gitscripts/default/testscenario.xml
<?xml version="1.0"?>
<scenario
    xmlns="https://dueca.tudelft.nl"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://dueca.tudelft.nl https://dueca.tudelft.nl/schemas/testscenario.xsd">
  <project name="FlexiStick">
    <window>DUECA/DUSIME control panel</window>
    <window>GUI stick</window>
  </project>
  <repository>git@gitlab.tudelft.nl:rvanpaassen/</repository>
  <execute>
    <platform>solo</platform>
    <node>solo</node>
  </execute>
  <actions>
    <check window="DUECA/DUSIME control panel"
	   x="10" y="10"  timeout="1.0"/>
    <click window="DUECA/DUSIME control panel"
	   x="400" y="20" button="0" pressed="false"/>
    <click window="DUECA/DUSIME control panel"
	   x="400" y="20" button="0" pressed="true"/>
    <check window="DUECA/DUSIME control panel"
	   x="10" y="10" r="0" g="255" b="0" timeout="1.0"/>
  </actions>
</scenario>

=== dueca/dueca/test/runtest/simplesimulation.xml
<?xml version='1.0' encoding='UTF-8'?>
<scenario xmlns="https://dueca.tudelft.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://dueca.tudelft.nl https://dueca.tudelft.nl/schemas/testscenario.xsd">
  <project name="SimpleSimulation">
    <window>DUECA/DUSIME control panel</window>
    <window>Are you serious?</window>
    <window>HID GUI</window>
    <window>front</window>
  </project>
  <repository>https://github.com/dueca/</repository>
  <execute>
    <platform>simlab</platform>
    <node>host</node>
  </execute>
  <execute>
    <platform>simlab</platform>
    <node>igtest</node>
  </execute>
  <offset x="1" y="-15"/>
  <actions>
    <!-- hold -->
    <!-- calibrate -->
    <check window="DUECA/DUSIME control panel" x="475" y="35" r="65" g="255" b="11" timeout="30.0" wait="0.5"/>
    <snap name="simplesimulation-000.png"/>
    <check window="DUECA/DUSIME control panel" x="475" y="75" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="475" y="75" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="475" y="75" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="475" y="79" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="474" y="118" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="474" y="118" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="474" y="118" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="476" y="120" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="258" y="136" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="258" y="136" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="475" y="204" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="475" y="204" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="475" y="204" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="475" y="204" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="424" y="201" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="424" y="201" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="424" y="201" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="424" y="201" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="477" y="244" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="477" y="244" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="477" y="244" button="Button.left" pressed="false" wait="0.2"/>
    <check window="HID GUI" x="131" y="69" r="250" g="250" b="250" timeout="10.0" wait="0.5"/>
    <click window="HID GUI" x="131" y="69" button="Button.left" pressed="true" wait="0.2"/>
    <click window="HID GUI" x="131" y="69" button="Button.left" pressed="false" wait="0.2"/>
    <click window="HID GUI" x="131" y="69" button="Button.left" pressed="true" wait="0.2"/>
    <click window="HID GUI" x="131" y="69" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="475" y="203" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="475" y="203" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="475" y="203" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="475" y="203" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="474" y="160" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="474" y="160" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="474" y="160" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="475" y="160" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="474" y="75" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="474" y="75" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="474" y="75" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="474" y="75" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <check window="DUECA/DUSIME control panel" x="475" y="35" r="104" g="104" b="104" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="475" y="35" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="475" y="35" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="475" y="35" r="65" g="255" b="11" timeout="10.0" wait="0.5"/>
    <click x="398" y="77" button="Button.left" pressed="true" wait="0.2"/>
    <click x="398" y="77" button="Button.left" pressed="false" wait="0.2"/>
    <check window="DUECA/DUSIME control panel" x="76" y="36" r="222" g="222" b="222" timeout="10.0" wait="0.5"/>
    <click window="DUECA/DUSIME control panel" x="76" y="36" button="Button.left" pressed="true" wait="0.2"/>
    <click window="DUECA/DUSIME control panel" x="76" y="36" button="Button.left" pressed="false" wait="0.2"/>
    <check window="Are you serious?" x="44" y="14" r="245" g="245" b="245" timeout="10.0" wait="0.5"/>
    <click window="Are you serious?" x="44" y="14" button="Button.left" pressed="true" wait="0.2"/>
    <click x="88" y="165" button="Button.left" pressed="false" wait="0.2"/>
    <click x="825" y="175" button="Button.left" pressed="true" wait="0.2"/>
    <click x="825" y="175" button="Button.left" pressed="false" wait="0.2"/>
    <click x="825" y="175" button="Button.left" pressed="true" wait="0.2"/>
  </actions>
</scenario>

=== dueca/dueca/test/runtest/triggering.xml
<?xml version='1.0' encoding='UTF-8'?>
<scenario xmlns="https://dueca.tudelft.nl"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://dueca.tudelft.nl https://dueca.tudelft.nl/schemas/testscenario.xsd">
  <project name="DuecaTestCommunication">
    <window>DUECA/DUSIME control panel</window>
    <window>Are you serious?</window>
  </project>
  <repository>https://github.com/dueca/</repository>
  <execute>
    <platform>solo</platform>
    <node>triggering</node>
  </execute>
  <actions>
    <check window="DUECA/DUSIME control panel" x="475" y="66" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <snap name="triggering-start.png" />
    <check window="DUECA/DUSIME control panel" x="481" y="109" r="104" g="104" b="104"
      timeout="10.0" wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="481" y="109" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="481" y="109" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="DUECA/DUSIME control panel" x="481" y="109" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="477" y="154" r="104" g="104" b="104"
      timeout="10.0" wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="477" y="154" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="477" y="154" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="DUECA/DUSIME control panel" x="143" y="107" r="0" g="0" b="0" timeout="10.0"
      wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="143" y="107" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="143" y="107" button="Button.left" pressed="false"
      wait="0.2" />
    <check wait="0.2" />
    <snap name="triggering-run.png" />
    <check wait="20.0" />
    <check window="DUECA/DUSIME control panel" x="477" y="150" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="477" y="108" r="104" g="104" b="104"
      timeout="10.0" wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="477" y="108" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="477" y="108" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="DUECA/DUSIME control panel" x="477" y="108" r="65" g="255" b="11" timeout="10.0"
      wait="0.5" />
    <check window="DUECA/DUSIME control panel" x="479" y="64" r="104" g="104" b="104" timeout="10.0"
      wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="479" y="64" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="479" y="64" button="Button.left" pressed="false"
      wait="0.2" />
    <check wait="2.5" />
    <click window="DUECA/DUSIME control panel" x="17" y="20" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="17" y="20" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="DUECA/DUSIME control panel" x="75" y="69" r="53" g="132" b="228" timeout="10.0"
      wait="0.5" />
    <click window="DUECA/DUSIME control panel" x="75" y="69" button="Button.left" pressed="true"
      wait="0.2" />
    <click window="DUECA/DUSIME control panel" x="75" y="69" button="Button.left" pressed="false"
      wait="0.2" />
    <check window="Are you serious?" x="37" y="65" r="248" g="248" b="247" timeout="10.0" wait="0.5" />
    <click window="Are you serious?" x="37" y="65" button="Button.left" pressed="true" wait="0.2" />
    <click window="Are you serious?" x="37" y="65" button="Button.left" pressed="false" wait="0.2" />
  </actions>
</scenario>
